// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from 'contentful'
import { Document } from '@contentful/rich-text-types'

export interface IBookFields {
  /** Name */
  name: string

  /** ISBN */
  isbn: string

  /** Rate */
  rate: number

  /** Body */
  body: string

  /** Tag */
  tag?: ITag[] | undefined

  /** PublishedAt */
  publishedAt: string

  /** ReadAt */
  readAt?: string | undefined

  /** State */
  state: 'bookshelf' | 'ebook' | 'rented'
}

export interface IBook extends Entry<IBookFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'book'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface ITagFields {
  /** Name */
  name: string

  /** Slug */
  slug: string
}

export interface ITag extends Entry<ITagFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'tag'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

type CONTENT_TYPE = 'book' | 'tag'

type LOCALE_CODE = 'ja-JP'

type CONTENTFUL_DEFAULT_LOCALE_CODE = 'ja-JP'
