// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from "contentful";
import { Document } from "@contentful/rich-text-types";

export interface IBookFields {
  /** Name */
  name: string;

  /** ISBN */
  isbn: string;

  /** Rate */
  rate: number;

  /** Body */
  body?: string | undefined;

  /** category */
  category?: ICategory | undefined;

  /** isRead */
  isRead?: boolean | undefined;

  /** State */
  state: "bookshelf" | "ebook" | "rented";

  /** PublishedAt */
  publishedAt: string;
}

export interface IBook extends Entry<IBookFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "book";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ICategoryFields {
  /** title */
  title: string;

  /** slug */
  slug: string;
}

export interface ICategory extends Entry<ICategoryFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "category";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export type CONTENT_TYPE = "book" | "category";

export type LOCALE_CODE = "ja-JP";

export type CONTENTFUL_DEFAULT_LOCALE_CODE = "ja-JP";
