name: Lint and Test
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master
      - chore/renovate
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: test
        run: |
          yarn install
          yarn build
          yarn lint
          yarn test:ci
